# ==========================================================================
# CHAINLINK CRE WORKFLOW SETTINGS
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "homeward-confidential-match-staging"
  workflow-artifacts:
    workflow-path: "workflow.ts"
    config-path: "config.staging.json"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  user-workflow:
    workflow-name: "homeward-confidential-match-production"
  workflow-artifacts:
    workflow-path: "workflow.ts"
    config-path: "config.staging.json"
